services:
  db:
    image: postgres:15
    container_name: xmltest_db
    environment:
      POSTGRES_USER: egor
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: xmltest
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  updater:
    build: .
    container_name: xml-parser-updater
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/xmltest
      DB_USER: egor
      DB_PASS: password123

volumes:
  db_data:
